os: osx
osx_image: xcode12.2
language: swift
script: xcodebuild clean test -project Spotify.xcodeproj -scheme "Spotify" -sdk iphonesimulator -destination "platform=iOS Simulator,OS=14.4,name=iPhone 11" ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO


